2025-03-18 15:58:10,231 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 15:58:10,231 [INFO] Starting Extract
2025-03-18 15:58:21,640 [INFO] Completed Extract in 11.41 seconds, memory used: 1831.45 MB, CPU used: 13.50%
2025-03-18 15:58:21,640 [INFO] Starting Transform
2025-03-18 15:58:37,764 [INFO] Completed Transform in 16.12 seconds, memory used: 1145.14 MB, CPU used: 13.60%
2025-03-18 15:58:37,764 [INFO] Starting Load
2025-03-18 16:03:14,678 [ERROR] Error generating query: 'function' object is not iterable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\modules\generate_query.py", line 201, in generate_query
    pk_value = row[pk_index]
TypeError: 'function' object is not iterable
2025-03-18 16:03:14,741 [ERROR] Error in Load (Attempt 1/3): 'function' object is not iterable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 62, in load
    query = generate_query(query_type=query_type, database_name=database_name, table=table_name, data=prepared_data, interval='12 DAY')
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\modules\generate_query.py", line 201, in generate_query
    pk_value = row[pk_index]
TypeError: 'function' object is not iterable
2025-03-18 16:03:14,741 [WARNING] Retrying Load in 2 seconds...
2025-03-18 16:28:07,628 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 16:28:07,628 [INFO] Starting Extract
2025-03-18 16:28:19,459 [INFO] Completed Extract in 11.83 seconds, memory used: 1843.96 MB, CPU used: 13.00%
2025-03-18 16:28:19,459 [INFO] Starting Transform
2025-03-18 16:28:35,498 [INFO] Completed Transform in 16.04 seconds, memory used: 1143.92 MB, CPU used: 13.50%
2025-03-18 16:28:35,498 [INFO] Starting Load
2025-03-18 16:28:37,462 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:37,462 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:37,462 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:37,462 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:37,462 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:37,462 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:37,526 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:28:37,526 [WARNING] Retrying Load in 2 seconds...
2025-03-18 16:28:41,045 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:41,045 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:41,045 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:41,045 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:41,045 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:41,045 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:41,067 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:28:41,067 [WARNING] Retrying Load in 4 seconds...
2025-03-18 16:28:46,782 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:46,782 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:46,782 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:46,782 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:46,782 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:28:46,782 [INFO] Invalid column: LINENUM. Skipping this column.
2025-03-18 16:28:46,801 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:28:46,801 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 16:28:46,801 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:30:53,992 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 16:30:53,992 [INFO] Starting Extract
2025-03-18 16:31:04,204 [INFO] Completed Extract in 10.21 seconds, memory used: 1853.82 MB, CPU used: 25.50%
2025-03-18 16:31:04,204 [INFO] Starting Transform
2025-03-18 16:31:20,434 [INFO] Completed Transform in 16.23 seconds, memory used: 1144.74 MB, CPU used: 16.30%
2025-03-18 16:31:20,434 [INFO] Starting Load
2025-03-18 16:31:22,543 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:22,599 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:22,609 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:22,635 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:31:22,635 [WARNING] Retrying Load in 2 seconds...
2025-03-18 16:31:26,128 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:26,142 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:26,160 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:26,188 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:31:26,188 [WARNING] Retrying Load in 4 seconds...
2025-03-18 16:31:31,749 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:31,770 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:31,779 [ERROR] Type mismatch: Cannot convert to UInt16 in column 'LINENUM'. Skipping this column.
2025-03-18 16:31:31,786 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:31:31,786 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 16:31:31,786 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:46:26,305 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 16:46:26,305 [INFO] Starting Extract
2025-03-18 16:46:36,950 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000124D13723D0>, 'Connection to ofvssfn5dd.us-central1.gcp.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-18 16:46:49,017 [INFO] Completed Extract in 22.71 seconds, memory used: 1860.98 MB, CPU used: 20.40%
2025-03-18 16:46:49,030 [INFO] Starting Transform
2025-03-18 16:47:07,143 [INFO] Completed Transform in 18.11 seconds, memory used: 1143.73 MB, CPU used: -31.00%
2025-03-18 16:47:07,143 [INFO] Starting Load
2025-03-18 16:47:09,236 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:09,262 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:09,277 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:09,297 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:47:09,298 [WARNING] Retrying Load in 2 seconds...
2025-03-18 16:47:12,830 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:12,850 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:12,869 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:12,895 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:47:12,895 [WARNING] Retrying Load in 4 seconds...
2025-03-18 16:47:18,442 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:18,465 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:18,477 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 16:47:18,486 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:47:18,486 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 16:47:18,486 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:56:22,372 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 16:56:22,372 [INFO] Starting Extract
2025-03-18 16:56:33,294 [INFO] Completed Extract in 10.92 seconds, memory used: 1858.01 MB, CPU used: 13.40%
2025-03-18 16:56:33,294 [INFO] Starting Transform
2025-03-18 16:56:53,612 [INFO] Completed Transform in 20.32 seconds, memory used: 1145.12 MB, CPU used: 15.30%
2025-03-18 16:56:53,612 [INFO] Starting Load
2025-03-18 16:56:55,779 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:56:55,779 [WARNING] Retrying Load in 2 seconds...
2025-03-18 16:56:59,334 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:56:59,334 [WARNING] Retrying Load in 4 seconds...
2025-03-18 16:57:04,966 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 16:57:04,966 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 16:57:04,966 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:00:37,275 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 17:00:37,275 [INFO] Starting Extract
2025-03-18 17:00:47,067 [INFO] Completed Extract in 9.79 seconds, memory used: 1855.83 MB, CPU used: 14.50%
2025-03-18 17:00:47,067 [INFO] Starting Transform
2025-03-18 17:01:07,469 [INFO] Completed Transform in 20.40 seconds, memory used: 1145.11 MB, CPU used: 13.80%
2025-03-18 17:01:07,469 [INFO] Starting Load
2025-03-18 17:01:09,524 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:09,555 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:09,570 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:09,592 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:01:09,592 [WARNING] Retrying Load in 2 seconds...
2025-03-18 17:01:13,117 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:13,133 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:13,143 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:13,158 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:01:13,158 [WARNING] Retrying Load in 4 seconds...
2025-03-18 17:01:19,045 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:19,070 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:19,079 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:01:19,095 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:01:19,095 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 17:01:19,095 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:25:08,050 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 17:25:08,050 [INFO] Starting Extract
2025-03-18 17:25:42,681 [INFO] Completed Extract in 34.63 seconds, memory used: 1849.88 MB, CPU used: 11.00%
2025-03-18 17:25:42,681 [INFO] Starting Transform
2025-03-18 17:26:03,636 [INFO] Completed Transform in 20.95 seconds, memory used: 920.54 MB, CPU used: 14.00%
2025-03-18 17:26:03,636 [INFO] Starting Load
2025-03-18 17:26:05,707 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:05,732 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:05,743 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:05,759 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:26:05,759 [WARNING] Retrying Load in 2 seconds...
2025-03-18 17:26:09,283 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:09,308 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:09,319 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:09,333 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:26:09,336 [WARNING] Retrying Load in 4 seconds...
2025-03-18 17:26:14,922 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:14,943 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:14,952 [ERROR] Type mismatch: Cannot convert to UInt64 in column 'LINENUM'. Skipping this column.
2025-03-18 17:26:14,961 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:26:14,961 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 17:26:14,961 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:28:12,185 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 17:28:12,185 [INFO] Starting Extract
2025-03-18 17:28:22,224 [INFO] Completed Extract in 10.04 seconds, memory used: 1856.05 MB, CPU used: 14.50%
2025-03-18 17:28:22,224 [INFO] Starting Transform
2025-03-18 17:28:43,300 [INFO] Completed Transform in 21.08 seconds, memory used: 921.05 MB, CPU used: 15.20%
2025-03-18 17:28:43,300 [INFO] Starting Load
2025-03-18 17:28:45,354 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:45,374 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:45,389 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:45,410 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:28:45,410 [WARNING] Retrying Load in 2 seconds...
2025-03-18 17:28:48,932 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:48,951 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:48,961 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:48,973 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:28:48,974 [WARNING] Retrying Load in 4 seconds...
2025-03-18 17:28:54,562 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:54,584 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:54,594 [ERROR] Type mismatch: Cannot convert '1.000000' to UInt64 in column 'LINENUM'. Skipping this row.
2025-03-18 17:28:54,603 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:28:54,603 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 17:28:54,608 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:50:05,051 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-18 17:50:05,055 [INFO] Starting Extract
2025-03-18 17:50:15,016 [INFO] Completed Extract in 9.96 seconds, memory used: 1865.08 MB, CPU used: 14.80%
2025-03-18 17:50:15,016 [INFO] Starting Transform
2025-03-18 17:50:38,690 [INFO] Completed Transform in 23.67 seconds, memory used: 1412.47 MB, CPU used: 13.80%
2025-03-18 17:50:38,690 [INFO] Starting Load
2025-03-18 17:50:41,512 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:50:41,512 [WARNING] Retrying Load in 2 seconds...
2025-03-18 17:50:45,620 [INFO] New records: 0, Updated records: 0
2025-03-18 17:50:45,854 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:50:45,854 [WARNING] Retrying Load in 4 seconds...
2025-03-18 17:50:52,147 [INFO] New records: 0, Updated records: 0
2025-03-18 17:50:52,450 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-18 17:50:52,450 [CRITICAL] Failed Load after 3 attempts.
2025-03-18 17:50:52,450 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 66, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 10:40:51,926 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-19 10:40:51,927 [INFO] Starting Extract
2025-03-19 10:41:03,434 [INFO] Completed Extract in 11.51 seconds, memory used: 1828.06 MB, CPU used: 11.50%
2025-03-19 10:41:03,442 [INFO] Starting Transform
2025-03-19 10:41:19,665 [INFO] Completed Transform in 16.22 seconds, memory used: 1411.75 MB, CPU used: -44.70%
2025-03-19 10:41:19,665 [INFO] Starting Load
2025-03-19 10:41:21,552 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 10:41:21,552 [WARNING] Retrying Load in 2 seconds...
2025-03-19 10:41:24,929 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 10:41:24,929 [WARNING] Retrying Load in 4 seconds...
2025-03-19 10:41:30,323 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 10:41:30,323 [CRITICAL] Failed Load after 3 attempts.
2025-03-19 10:41:30,323 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 11:01:36,901 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-19 11:01:36,902 [INFO] Starting Extract
2025-03-19 11:01:49,004 [INFO] Completed Extract in 12.10 seconds, memory used: 1826.16 MB, CPU used: 17.30%
2025-03-19 11:01:49,004 [INFO] Starting Transform
2025-03-19 11:02:05,503 [INFO] Completed Transform in 16.50 seconds, memory used: 1412.08 MB, CPU used: 13.70%
2025-03-19 11:02:05,504 [INFO] Starting Load
2025-03-19 11:02:08,385 [ERROR] Error in Load (Attempt 1/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 11:02:08,386 [WARNING] Retrying Load in 2 seconds...
2025-03-19 11:02:12,587 [ERROR] Error in Load (Attempt 2/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 11:02:12,588 [WARNING] Retrying Load in 4 seconds...
2025-03-19 11:02:19,413 [ERROR] Error in Load (Attempt 3/3): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 11:02:19,414 [CRITICAL] Failed Load after 3 attempts.
2025-03-19 11:02:19,414 [CRITICAL] ETL Pipeline failed for job: gc_salesline — Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 137, in run_etl_pipeline
    load(transformed_data, logger)
  File "c:\Users\PC\Work\VTA\GitAn\vta-test\src\etl\logs\etl_logger.py", line 78, in wrapper
    result = func(*args, **kwargs)
  File "c:/Users/PC/Work/VTA/GitAn/vta-test/src/etl/etl_gc_salesline.py", line 67, in load
    logger.info(f"Generated query: {query[:100]}...")
TypeError: 'NoneType' object is not subscriptable
2025-03-19 11:06:29,621 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-19 11:06:29,621 [INFO] Starting Extract
2025-03-19 11:06:41,401 [INFO] Skipping processing of raw/SALESLINE.parquet. The file is not newer than the table.
2025-03-19 11:06:41,589 [INFO] Completed Extract in 11.97 seconds, memory used: 959.89 MB, CPU used: 13.50%
2025-03-19 11:06:41,589 [INFO] ETL Pipeline completed for job: gc_salesline in 11.97 seconds, total memory used: 959.89 MB, total CPU used: 0.00%
2025-03-19 11:18:24,999 [INFO] ETL Pipeline started for job: gc_salesline
2025-03-19 11:18:24,999 [INFO] Starting Extract
2025-03-19 11:18:37,724 [INFO] Completed Extract in 12.72 seconds, memory used: 1881.09 MB, CPU used: 13.10%
2025-03-19 11:18:37,724 [INFO] Starting Transform
2025-03-19 11:18:58,649 [INFO] Completed Transform in 20.93 seconds, memory used: 1409.37 MB, CPU used: 25.30%
2025-03-19 11:18:58,649 [INFO] Starting Load
2025-03-19 11:19:01,124 [INFO] Query of type 'INSERT' for table prod_source.salesline has been generated.
2025-03-19 11:19:01,124 [INFO] Completed Load in 2.47 seconds, memory used: 0.34 MB, CPU used: 22.20%
2025-03-19 11:19:01,124 [INFO] ETL Pipeline completed for job: gc_salesline in 36.13 seconds, total memory used: 3290.80 MB, total CPU used: 0.00%
